ABSOLUTE_LOGGING_PATH = r"C:\LOCAL_REPO\py_ExergyUtilities\LoggingConfig\loggingNofile.conf"
IDF_TEMPLATE_PATH = r"C:\LOCAL_REPO\ref_energyDB\IDF_Templates"
FREELANCE_DIR = r"C:\Dropbox\16336 LIDL\\"
IDD_FILE_PATH = r"C:\LOCAL_REPO\py_LEED_IDF_ESO\IDD\EnergyPlus 8 6 0.idd"
IDD_XML_FILE_PATH = r"C:\LOCAL_REPO\py_EnergyParser\IDD_XML\IDD_860.xml"
